version: '2.4'
services:
  db:
    image: mysql
    container_name: to_do_list
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - to_do_list_data:/var/lib/mysql

volumes:
  to_do_list_data:
